-- This is an empty migration.-- This is an empty migration.
-- https://stackoverflow.com/questions/69023136/auto-incrementing-from-custom-value-in-prisma-postgresql
-- ALTER SEQUENCE schema01.batch_execution_time_id_seq RESTART WITH 100;
-- ALTER SEQUENCE schema01.batch_execution_time_id_seq START  100;
-- ALTER SEQUENCE schema01.batch_execution_time_id_seq MINVALUE  100;
-- ALTER SEQUENCE schema01.batch_execution_time_id_seq  INCREMENT BY 20;
